### ISSUE TITLE
Adding video chat UI and related methods (Swift)

### ISSUE THREAD

**Issue by zoufishanmehdi** [opentok/opentok-ios-sdk-samples-swift#1]
Hi Rob, I stumbled upon your project in swift via opentok ios sdk samples. I'm integrating opentok video chat in my swift project. I was able to successfully do so using this [sample project](https://github.com/thepatrick/Opentok-HelloWorld-Swift). I wanted to add video chat UI and related methods in swift i.e. volume/ mute and flip camera buttons.  While looking thru ios sdk samples in objective-c, it's unclear what methods are related to this functionality. How can I add this functionality to my swift project? Your input would be much appreciated.

**Comment by robjperez** [comment]
Hi Zoufishan,

These samples are still Work In Progress.
We will be adding more samples in the near future and we will cover that use case

**Comment by Lucashuang0802** [comment]
@robjperez @zoufishanmehdi perhaps `OTVideoView` in this(https://github.com/opentok/accelerator-core-ios) could help you out. You can use the default UI or customize your own.
