### ISSUE TITLE
Switching camera in 2.Custom-Video-Driver

### ISSUE THREAD

**Issue by klemensz** [opentok/opentok-ios-sdk-samples-swift#10]
Hi,
it seems that the ExampleVideoCapture.swift always uses the front camera - hard coded. What would we need to change so that setting publisher.cameraPosition would have an effect like with the framework classes?
Thanks!

**Comment by robjperez** [comment]
In current master branch you can toggle the camera position.

See this [PR](https://github.com/opentok/opentok-ios-sdk-samples-swift/pull/28) for more details
