### ISSUE TITLE
How to take screenshot of webview with playing video?

### ISSUE THREAD

**Issue by danielCarlosCE** [opentok/opentok-ios-sdk-samples-swift#100]
`ScreenCapturer` works very well for most cases I need, but when there's a video playing on my webview, its content is not on the screenshot sent. How can one take screenshot of whole view including video content? 

Thanks,

**Comment by jgorozco** [comment]
i see that in objective c was updated (https://github.com/opentok/opentok-ios-sdk-samples/blob/master/Screen-Sharing/Screen-Sharing/TBScreenCapture.m ) have any plan to update this code to swift?? :-)
