### ISSUE TITLE
ScreenCapturer using Main Thread and Taking too much CPU

### ISSUE THREAD

**Issue by danielCarlosCE** [opentok/opentok-ios-sdk-samples-swift#101]
`UIView.drawHierarchy(in:afterScreenUpdates:) must be used from main thread only`
`UIView.bounds must be used from main thread only`

Beside those warning whenever I start sharing screen, the CPU use goes from 30% to 100% until the app crashes.

**Comment by vncmaciel** [comment]
Same here

**Comment by tatuanfpt** [comment]
@danielCarlosCE : Have you find solution yet ?
