### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by findigital** [opentok/opentok-ios-sdk-samples-swift#102]
I've applied my APIkey, session ID and tokens to a few different sample projects and on immediate open of the build on the device I receive the following error "Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)" and the line below:

import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

----

I'm stuck testing since none of the sample builds I tested do not work for me and generate the same error. I've tried creating new apps within Tokbox but that does not resolve the issue either. I've been able to create working web sample apps using the creds provided but not iOS apps.

**Comment by RohitiOSDeveloper** [comment]
Simple way you can solve this issue by update pod .
