### ISSUE TITLE
What's the equivalent of Session.StreamPropertiesListener on iOS?

### ISSUE THREAD

**Issue by danielCarlosCE** [opentok/opentok-ios-sdk-samples-swift#104]
I have two users in the session. User A and user B. On User A's application I want to be able to show if user B is muted or not. 

I've tried the property observer 
```
audioObserver = stream.observe(\.hasAudio) {  (stream: OTStream, change) in }
```
It works if user B is only streaming it's camera/audio. But as soon as user B starts a screen stream, the observer is not called any longer. It seems you create a new `OTStream` underneath. 

Thanks

**Comment by saikumar-zapoj** [comment]
Hi @danielCarlosCE facing the same issue could you please elaborate on the code.

**Comment by vodemn** [comment]
Any updates on this?)
