### ISSUE TITLE
Cocoapods Spec is broken.

### ISSUE THREAD

**Issue by pkondrashkov** [opentok/opentok-ios-sdk-samples-swift#106]
Currently when I try to install any version of OpenTok it fails on unarchiving sdk. 
```
[!] Error installing OpenTok
[!] /usr/bin/tar xfj /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/d20200320-3571-ne1jid/file.tbz -C /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/d20200320-3571-ne1jid
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```
Actually the reason is `https://tokbox.com/downloads/OpenTok-iOS-2.16.5.tar.bz2` seems to be broken. Instead of responding with actual archive it redirects to your home page: `https://www.vonage.com/communications-apis/video/`

And any other links really. `https://tokbox.com/downloads/OpenTok-iOS-2.14.2.tar.bz2` is also broken, which I need in order to build the project  😕

To be honest I tried to contact support on your site but it is really hard to find the way how to do so, seems like nothing was related to OpenTok support.

Please let me know if any information is needed from my side. 

Thanks!

**Comment by bricepollock** [comment]
Getting this same issue starting yesterday

**Comment by msach22** [comment]
Hi team, apologies for this. We had an issue with the server hosting the SDKs, but that's now been resolved. You should be able to download this via Cocoapods or even directly. 

I've just validated it from different endpoints.

**Comment by pkondrashkov** [comment]
Thanks for quick actions and response! Have a good day!

**Comment by msach22** [comment]
Happy to help, apologies for the issue :)
