### ISSUE TITLE
Question - how to mock OTSession object?

### ISSUE THREAD

**Issue by hkellaway** [opentok/opentok-ios-sdk-samples-swift#113]
Hello -

I'm trying to write unit tests around my Tokbox integration - however, this is quickly stymied by the fact that `OTSession` objects cannot be mocked given they require a valid API Key and Session ID association. 

Given I'm trying not to connect to the actual TokBox service to enact unit tests - any suggestions on how to proceed?

**Comment by abdulajet** [comment]
You can create a subclass of `OTSession` in objc which will allow you to create an init which bypassed the required ones

**Comment by hkellaway** [comment]
this was asked over 1 year ago 😳
