### ISSUE TITLE
Publisher is not publishing for unknown reason

### ISSUE THREAD

**Issue by ShengJunDong89** [opentok/opentok-ios-sdk-samples-swift#120]
This happens infrequently, maybe once every 10-20 sessions. When publishing, there's no callback on whether publish succeed or failed.
When session is connected, the delegate callback `sessionDidConnect(_ session: OTSession)` is called. Once that happen, publish is called `session.publish(publisher, error: &error)`.
At this point there's no error, and the async delegate error handler `func publisher(_ publisher: OTPublisherKit, didFailWithError error: OTError)` is not called. There's no publisher stream created.
Everything else works, such as subscribing to others streams.

**Comment by saikumar-zapoj** [comment]
i have got same issue any solution please
