### ISSUE TITLE
 turn off and on speaker is not working in iOS Swift

### ISSUE THREAD

**Issue by saikumar-zapoj** [opentok/opentok-ios-sdk-samples-swift#124]
I have used the below code for Turn off and on for Speaker it works well in Webrtc native. but it's not working while using Opentok. by default opentok is enabling the speaker but I don't want to come up with speaker at initial. please suggest me any solution.

func enableSpeaker(isSpeaker: Bool) {
    
    
    let audioSession = AVAudioSession.sharedInstance()
    do {
        try audioSession.setCategory(AVAudioSessionCategoryPlayAndRecord)
    } catch let error as NSError {
        print("setCategory error: \(error.localizedDescription)")
    }
    
    if isSpeaker{
        do {
            try audioSession.overrideOutputAudioPort(AVAudioSessionPortOverride.speaker)
        } catch let error as NSError {
            print("audioSession error: \(error.localizedDescription)")
        }
    }else{
        do {
            try audioSession.overrideOutputAudioPort(AVAudioSessionPortOverride.none)
        } catch let error as NSError {
            print("audioSession error: \(error.localizedDescription)")
        }
    }
}

**Comment by saikumar-zapoj** [comment]
@robjperez please help me with this.

**Comment by aayubhagat** [comment]
I am also facing the same issue.
When i set audioport none it doesn't work. Bydefault speaker is active.Please help me on this.

**Comment by gotozainishaikh** [comment]
yes i also have same issue.

**Comment by fukemy** [comment]
same problem here, did someone solved this?

**Comment by v-kpheng** [comment]
This may help: https://stackoverflow.com/questions/50132396/callkit-issue-with-speaker-automatically-turned-on-after-receiving-the-call/50460757#50460757

Also, it's not clear if you're working with a custom audio driver.  If issue persists, please refile.  Thanks!
