### ISSUE TITLE
How can I share the whole screen that currently displayed and not specific view controller?

### ISSUE THREAD

**Issue by aviya-smila** [opentok/opentok-ios-sdk-samples-swift#125]
Hi, 
I'm writing an app where I need the to share the whole screen which is assambled from VCs, AV camera previews and more.
I want to share the whole displayed screen(including camera preview with AV layer).
how can I achieve this?

**Comment by v-kpheng** [comment]
@aviya-smila, apologies for the belated reply.

https://github.com/opentok/opentok-ios-sdk-samples-swift/tree/main/Screen-Sharing should help.  Any other issues, please let us know.  Thanks!
