### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by rextremotabaresDtt** [opentok/opentok-ios-sdk-samples-swift#130]
Hello,
my company has a paid account for Opentok and I'm migrating our App dependencies to SPM. OpenTok is using Cocoapods but I'm wondering if there are any plans to allow integration with Swift Package Manager (which is getting more and more support from Apple itself such as [supporting binary libraries ](https://developer.apple.com/videos/play/wwdc2020/10147/)) or if it's already done how can we configure the dependency for Opentok. 
Thank you

**Comment by xezero** [comment]
+1 on SPM support!

**Comment by Vonage-Aida** [comment]
@rextremotabaresDtt  @xezero  thanks for your interest on SPM support, I filled the product request for this feature. 

Thanks, 
Aida

**Comment by hkellaway** [comment]
hi @Vonage-Aida 👋 any movement on this one? thanks!

**Comment by egarni** [comment]
+1 for adding SPM support! OpenTok is the only dependency I have not supporting SPM =^(

**Comment by DogeWowzie** [comment]
@egarni same here, Opentok is the only dependency blocking me from removing CocoaPods completely. Are there any plans to add SPM support?

**Comment by Bastianowicz** [comment]
@DogeWowzie same here. This is a serious problem to us and we have to evaluate other providers in case this cannot be resolved. What are your plans regarding this issue?

**Comment by jweg29** [comment]
@Vonage-Aida @abdulajet is there any timeline for supporting Apple's Swift Package Manager? Similar to what others have said OpenTok is the only dependency in my project that has not added support yet.

**Comment by abdulajet** [comment]
I can bump the request with engineering. Thanks for the patience

**Comment by DRK1004** [comment]
+1 for adding SPM support! Is there any expected timeline for supporting SPM?

**Comment by mehmetbaykar** [comment]
+1 for adding SPM support!

**Comment by samitaha2** [comment]
+1 for adding SPM support

**Comment by vidueirof** [comment]
+1 SPM support

**Comment by rextremotabaresDtt** [comment]
Any update on this?

**Comment by mvarie** [comment]
+1 for adding SPM support

**Comment by Lontronix** [comment]
Would love to see SPM support added as well.

**Comment by jffmrk** [comment]
+1 🤞

**Comment by ben-palmer** [comment]
Yes please!

**Comment by falkobuttler** [comment]
+1 here. Unfortunately, the latest versions of OpenTok or OTXCFramework do not seem to work with Xcode on M1 Macs, while SPM packages of incompatible CocoaPods packages worked fine.

**Comment by ben-palmer** [comment]
@Vonage-Aida - is there any timeline for spm support?

**Comment by murillotomas** [comment]
Come on OpenTok. I has been 1.5 years already since this was requested and no sight on the horizon for SPM yet.
On top of that you guys make money with this. You should be taking a little bit more care of your customers.

**Comment by maxxfrazer** [comment]
Seems swiftpm isn't happening for opentok (yet).
It does work with Agora.io though for almost a year now (I work there, full disclosure), maybe the opentok team would find the motivation if others are doing it already 😉

- [Core SDK](https://github.com/AgoraIO/AgoraRtcEngine_iOS)
- [Video UIKit](https://github.com/AgoraIO-Community/iOS-UIKit)

Also works fully with M1 Macs - why do some businesses find this requirement so hard to meet? 🤷

**Comment by samitaha2** [comment]
Agora probably has less bugs too

**Comment by ben-palmer** [comment]
@Vonage-Aida any roadmap updates on SPM support?

**Comment by tumata** [comment]
+1 for adding SPM support

**Comment by MattKiazyk** [comment]
> Looks like (a first step at least) is coming with 2.23.0 - https://tokbox.com/developer/sdks/ios/
> 
> `Version 2.23.0 of the SDK will not be packaged as a universal FAT framework. It will be packaged as an XCFramework.`

Looks like this didn't happen! 😢

**Comment by tumata** [comment]
The `XCFramework` looks available but is lacking some architectures (if I remember well, the M1 Simulator).

See: https://github.com/opentok/opentok-ios-sdk-samples/blob/main/Basic-Video-Chat-XCFramework/Podfile

**Comment by samitaha2** [comment]
So is this happening?

**Comment by MattKiazyk** [comment]
⏳ 

Can I say please?

**Comment by DogeWowzie** [comment]
Can confirm own Swift Package from `OpenTok.xcframework` works both on Apple Silicon and Intel Macs (tested running on Simulator and Real Devices)

Within `Basic-Video-Chat-XCFramework` I just ran `pod install` and created an own swift package with the `OpenTok.xcframework` output located in `Pods/OTXCFramework`. 

I placed it in the main directory of my swift package and added following manifest:

`let package = Package(
    name: "OpenTok",
    platforms: [
        .iOS(.v12)
    ],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "OpenTok",
            targets: ["OpenTok"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
    ],
    targets: [
        .binaryTarget(name: "OpenTok", path: "OpenTok.xcframework")
    ]
)`

I wanted to host this package for everyone to download, but upload limit of Github is not allowing me to do so. Was able to upload my package on the private company server though.

Instead of dropping the huge `OpenTok.xcframework` into your swift package directory you can also host a zip file of it and reference the url in your manifest like so:

` .binaryTarget(name: "OpenTok", url: <YourURL>, checksum: <YourChecksum>`

**Comment by maxxfrazer** [comment]
@DogeWowzie with the M1 simulator? That's the piece that wasn't working.

The xcframework from the pod location (https://s3.amazonaws.com/artifact.tokbox.com/rel/otkit-ios-sdk-xcframework/OpenTok-iOS-2.23.1.tar.bz2) doesn't have the right architectures

**Comment by DogeWowzie** [comment]
> @DogeWowzie with the M1 simulator? That's the piece that wasn't working.
> 
> The xcframework from the pod location (https://s3.amazonaws.com/artifact.tokbox.com/rel/otkit-ios-sdk-xcframework/OpenTok-iOS-2.23.1.tar.bz2) doesn't have the right architectures

Can confirm it worked like a charm on Apple Silicon and Intel machines, performed test runs on both simulator and real device. Please not i ran `pod install` on a M1 machine.

<img width="676" alt="Bildschirmfoto 2022-09-18 um 15 20 38" src="https://user-images.githubusercontent.com/8918704/190904425-6669f84e-19ac-435f-9e5e-e1c8f2c0209c.png">

**Comment by DogeWowzie** [comment]
> @DogeWowzie with the M1 simulator? That's the piece that wasn't working.
> 
> The xcframework from the pod location (https://s3.amazonaws.com/artifact.tokbox.com/rel/otkit-ios-sdk-xcframework/OpenTok-iOS-2.23.1.tar.bz2) doesn't have the right architectures

Thanks for pointing out my mistake. Unfortunately I forgot to uncheck "open with Rosetta" yesterday. 

When run on a M1 simulator, I receive following errors:
<img width="296" alt="Bildschirmfoto 2022-09-18 um 18 07 37" src="https://user-images.githubusercontent.com/8918704/190919464-49d3c723-f79d-422a-aeb7-35b644baa27e.png">

`file is universal (i386.x86 64) but does not contain the arm64 architecture`

**Comment by DogeWowzie** [comment]
Simulators run on a M1 with iOS 13.7 or below work though (they don't have an arm64 executable)

**Comment by murillotomas** [comment]
I got my reply here:
https://github.com/opentok/opentok-ios-sdk-samples/issues/258#issuecomment-1254274639

Apparently they are not supporting SPM...

**Comment by MattKiazyk** [comment]
In Xcode 14.3 (currently in Beta). Apple has removed support for Xcode running under Rosetta. Hope including arm64 is available soon!

![image](https://user-images.githubusercontent.com/1119565/219758029-a8b29c85-8480-40fc-bbcc-2c4f7370860a.png)

**Comment by vona-ben** [comment]
Note: We are currently working on an iOS SDK Swift Package Manager, which will be available soon. I will keep you updated on the progress in this thread
