### ISSUE TITLE
[ERROR] otk_webrtc_video_track_source.cpp:105 ProvideFrame Error converting video frame.

### ISSUE THREAD

**Issue by hkellaway** [opentok/opentok-ios-sdk-samples-swift#145]
Hello 👋 Without changing anything about my TokBox integration, i've randomly started encountering an error like this periodically:
`[ERROR] otk_webrtc_video_track_source.cpp:105 - [0x7fb0d94e1390]ProvideFrame Error converting video frame.`

It is logged to the console indefinitely over and over

I am integrating TokBox via CocoaPods; pod version `2.19.0`

When starting usage, there is also a message in the console from TokBox that says:
```
*********************** OpenTok iOS SDK ****************************
**** Version/Revision: ios-2.19.0/a9d768b8ead19c9f91a1d99c1641632b7387f5de
**** Library built on: Feb 11 2021
**** Copyright 2021 TokBox, Inc.
**** Licensed under the Apache License, Version 2.0
****
```

**Comment by chathurka** [comment]
https://tokbox.com/developer/sdks/ios/release-notes.html#known-issues

**Comment by danhilton1** [comment]
I am also seeing this repeated message in the console.
