### ISSUE TITLE
Publisher view  black screen issue when app goes to background

### ISSUE THREAD

**Issue by engrossinfotechtest** [opentok/opentok-ios-sdk-samples-swift#147]
Publisher view is turned to black when app goes to background in swift . Even while keeping the session alive and enabling background modes (and keeping audio session enabled in background mode)
So audio seems to work fine.
While the publisher returns back to foreground.
view is not restored while  the subscriber view is restored in the same situation .

I am using the latest **OPENTOK** library  OpenTok 2.19.0(Some how 2.19.2 is not getting installed) 

but still this issue persists

Please help. Thank you

**Comment by brycerker** [comment]
getting this one too. and publisher camera freezes too

**Comment by v-kpheng** [comment]
Apologies for the belated reply.  Cameras can't be used when in background mode: https://tokbox.com/developer/sdks/ios/background-state.html.

To clarify, is the issue that publisher remains black after entering the foreground?
