### ISSUE TITLE
Excessive direct access warnings present in 2.19.0 "direct access in function webrtc::" "direct access in function rtc::" "direct access in function cricket::"  etc.

### ISSUE THREAD

**Issue by hkellaway** [opentok/opentok-ios-sdk-samples-swift#148]
There are excessive warnings produced by the OpenTok library, all starting with `direct access in function`. Excessive equals magnitude of 1000+. 

Downgrading from `2.19.0` to `2.18.1` resolved the issue.

Here's a similar thread from Realm: https://github.com/realm/realm-cocoa/issues/6688

![opentok-errors](https://user-images.githubusercontent.com/5456481/114041045-2d51ae00-9852-11eb-878e-b19fbbba5502.png)

**Comment by rextremotabaresDtt** [comment]
Any update on this? Still seeing this huge amount of warnings...

**Comment by hkellaway** [comment]
this is resolved with version `2.20.0`
