### ISSUE TITLE
Timed out while attempting to publish.

### ISSUE THREAD

**Issue by milanpatoliya** [opentok/opentok-ios-sdk-samples-swift#156]
I have use Video calling but sometimes I get 
"Publisher failed: Error Domain=OTSessionErrorDomain Code=1541 "Timed out while attempting to publish." UserInfo={NSLocalizedDescription=Timed out while attempting to publish.}
 error how can I get a solution for this 
also not show detailed error

**Comment by anis-applocum** [comment]
Are you using any custom audio drivers?

**Comment by milanpatoliya** [comment]
> Are you using any custom audio drivers?

No I have used call kit now I gat SDK:- 2.20.2
Error :- Error setting up audio session Error Domain=NSOSStatusErrorDomain Code=1701737535 "(null)" I get this error from custome-Audio-Driver

**Comment by mehmetbaykar** [comment]
> Are you using any custom audio drivers?

I have the same error and happens when I use the DefaultAudio Driver from OpenTok.
Any idea what might be the issue?

**Comment by milanpatoliya** [comment]
you have used a call kit?

**Comment by mehmetbaykar** [comment]
No

**Comment by shweta48** [comment]
i am using callkit and face this problem after voip
