### ISSUE TITLE
DefaultAudioDevice should be updated

### ISSUE THREAD

**Issue by mehmetbaykar** [opentok/opentok-ios-sdk-samples-swift#157]
DefaultAudioDevice.swift in Custom-Audio-Driver is no working as expected. I have been using the objc code of OTDefaultAudioDevice.m and it works fine. Can you please make an update on DefaultAudioDevice.swift?

Thanks,

**Comment by v-kpheng** [comment]
@mehmetbaykar, apologies for the belated reply.  We tested this recently and it seems to be working.

Closing, since we can't reproduce.
