### ISSUE TITLE
How to receive signals in a session

### ISSUE THREAD

**Issue by 1755143168** [opentok/opentok-ios-sdk-samples-swift#166]
I will not receive signals in the session

**Comment by 1755143168** [comment]
<img width="836" alt="截屏2021-10-13 下午5 49 30" src="https://user-images.githubusercontent.com/73882342/137110208-1e4354dd-4e54-4a95-8bba-7f0e0152cb26.png"
<img width="1006" alt="截屏2021-10-13 下午5 49 47" src="https://user-images.githubusercontent.com/73882342/137110269-11c89860-953f-4520-8ae1-dd90738fe9af.png">
>

**Comment by v-kpheng** [comment]
Thanks, @1755143168, for filing this issue.  We'll add a sample application that'll showcase how to use this API: https://jira.vonage.com/browse/OPENTOK-49708.

That said, there's no ETA for this.  Sorry.

**Comment by v-kpheng** [comment]
@1755143168, see example here: https://github.com/opentok/opentok-ios-sdk-samples-swift/tree/main/Signals.

Hope that helps.  Closing.
