### ISSUE TITLE
Opentok initialization crash on iOS 15

### ISSUE THREAD

**Issue by TheMakerOleguch** [opentok/opentok-ios-sdk-samples-swift#168]
Hi, there is broken behavior upon initializing opentok, using the latest react-native 0.66 and pod version 2.20.2.
We receive a crash when opentok tries to initialize itself.
![image](https://user-images.githubusercontent.com/16706446/146770734-d8dec693-ac6d-4481-b56c-93761f4b2ebe.png)

**Comment by britolucaspatrick** [comment]
happens here too

**Comment by v-kpheng** [comment]
Thanks for letting us know about this.  Version 2.20 is no longer supported.  Also, more recent versions of React native have been released, which may have resolved the issue you're seeing.

If you're still able to reproduce the issue using more recent versions of the SDK, please refile.  Thanks!
