### ISSUE TITLE
Memory Leak in raptor_v2 json methods

### ISSUE THREAD

**Issue by knightcode** [opentok/opentok-ios-sdk-samples-swift#169]
Instruments is reporting small memory leaks in json_pack and json_object_set_new_nocheck, e.g. (and not the only stack trace):

![Screen Shot 2021-12-28 at 9 10 20 AM](https://user-images.githubusercontent.com/1806693/147574717-9d7fdead-9463-4f46-b234-852560a4b162.png)

These don't seem to consume more than 10s and 100s of bytes at a time. But, with a 50MB limit for the broadcast extension, we all have to do our jobs perfectly. I'm not sure how often these calls occur, but I imagine as the screen recording goes on, they'll pile up. And I think the paranoia here is somewhat warranted.

**Comment by v-kpheng** [comment]
Thanks, @knightcode, for letting us know about this issue.  Quite a few memory leak issues were fixed since this was filed.  If you're still seeing memory leak issues, please re-file.  Thanks!
