### ISSUE TITLE
FrameMetadata isn't working

### ISSUE THREAD

**Issue by JulianDMartinez** [opentok/opentok-ios-sdk-samples-swift#170]
The FrameCaptureMetadataDelegate methods are not called and the timestamp label is linked directly to the publisher's video capture, so it doesn't represent the received metadata from the stream by the subscribed. Also it seems that metadata is not transferred when `consumeImageBuffer` is used (since it is received as nil by the subscriber) but it does work with `consumeFrame`

The sample overall requires some work from the user to be able to test the metadata transfer functionality.

**Comment by v-kpheng** [comment]
Closing given lack of feedback.  If issue still persists, please refile.  Thanks!
