### ISSUE TITLE
Crash when Accessing Streams property of OTSession

### ISSUE THREAD

**Issue by mehmetbaykar** [opentok/opentok-ios-sdk-samples-swift#172]
I receive a crash when I try to access the streams property of OTSession. The moment I try to read this value **NSDictionary<NSString*, OTStream*>* _Nonnull streams** the app crashes.

Crash Log:
`Could not cast value of type 'OTStream' (0x10e60ba28) to 'OTStream' (0x115468e88).
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib`

Xcode version: 13.2 (13C90)

Devices used: iPhone 11 iOS 15.3, iPad Pro (11") 3rd generation 15.3

**Comment by ravkooashishraval** [comment]
Same issue with me...

**Comment by v-kpheng** [comment]
Thanks for letting us know about this issue.  Is this reproducible on the latest version of the SDK?  Also, do you have a snippet of the code that'll reproduce the issue.

Please advise.  Thanks!

**Comment by v-kpheng** [comment]
Closing, given lack of information. If this problem still persists, please refile. Thanks!
