### ISSUE TITLE
Sync Custom-audio-driver with Objective C repo

### ISSUE THREAD

**Issue by vona-ben** [opentok/opentok-ios-sdk-samples-swift#175]
There are a few commits missing which include fixes when using Bluetooth for custom audio driver

- [OPENTOK-46715: iOS Custom Audio Driver sync with SDK implementation ](https://github.com/opentok/opentok-ios-sdk-samples/commit/ded43e5d9080abd2c5c2ea7bdf266f7440c5dbf5)
- [Audio debug logs - more statements added ](https://github.com/opentok/opentok-ios-sdk-samples/commit/0d20648a48a54942f8f0bc0cb6541d28d8a7be0a)
- (maybe optional) [OPENTOK-47901: ringtone publisher start timeout error fixed ](https://github.com/opentok/opentok-ios-sdk-samples/commit/a4397ba9d9ebcb8c807ea3c0c282e3557e146385)

**Comment by vona-ben** [comment]
cc @chetanvangadiTokbox

**Comment by v-kpheng** [comment]
@vona-ben, thanks for letting us know about this.  No idea if any work is still pending.  If there is, can you please file a jira ticket and CC me on it?  Thanks!
