### ISSUE TITLE
application Crashed

### ISSUE THREAD

**Issue by ravkooashishraval** [opentok/opentok-ios-sdk-samples-swift#181]
`self.networkTest?.runConnectivityTest(withApiKey: tokBoxApiKey, sessionId: sessionId, token: token, executeQualityTest: true, qualityTestDuration: 10, delegate: self) `         

Xcode 14
pod 'OpenTok', '2.23.0'
<img width="1509" alt="Screenshot 2022-10-21 at 3 08 52 PM" src="https://user-images.githubusercontent.com/111400313/197165578-9f77f8ad-c62a-4494-b339-366bfed0ea08.png">

**Comment by v-kpheng** [comment]
Hi, @ravkooashishraval.  Thanks for letting us know about this issue.  Some key details are missing though, which may make root cause difficult.  Can you please refile this issue and answer the questions asked in our `Bug Report` template?  By doing so, it'll help make root cause easier.  Thanks!
