### ISSUE TITLE
iOS 16 "Timed out while attempting to publish."

### ISSUE THREAD

**Issue by knightcode** [opentok/opentok-ios-sdk-samples-swift#183]
Prior to iOS 16, we were able to initiate and publish to a session in response to a PushKit notification, which elevated the app's priority and allowed a session to form while the app remained in the background, maybe with the system's Call UI visible to the user via CallKit (if audio-only). 

With iOS 16, the OTPublisher seems to be having trouble. The OTSession can be created, incoming streams are announced, session.subscribe() is successful, and even session.publish() returns no error. But the OTPublisherDelegate.publisher(didFailWithError:) method is called after a few seconds with an undocumented code of 1541 and a message saying "Timed out while attempting to publish." The result is a state where the user can (see and) hear all the other participants, but they do not (see or) hear the iOS user.

There's no trouble if the session is initiated through the app's UI while the app is active.

There also seems to be a race condition somewhere in if the user can click through the CallKit UI fast enough to bring the app into the foreground before..._something_.. happens, publishing succeeds. We haven't determined what that _something_ is.

Moreover, when it's on its way to timing out, someone's code is polluting the console with these errors, which seem germane to this issue:
```
App[13956:3993378] [aurioc]            AURemoteIO.cpp:1139  failed: 561017449 (enable 1, outf< 1 ch,      0 Hz, Float32> inf< 1 ch,  48000 Hz, Int16>)
App[13956:3993378] [aurioc]            AURemoteIO.cpp:1139  failed: 561017449 (enable 1, outf< 1 ch,      0 Hz, Float32> inf< 1 ch,  48000 Hz, Int16>)
App[13956:3993378] [aurioc]            AURemoteIO.cpp:1139  failed: 561017449 (enable 1, outf< 1 ch,      0 Hz, Float32> inf< 1 ch,  48000 Hz, Int16>)
App[13956:3993378] [aurioc]            AURemoteIO.cpp:1139  failed: 561017449 (enable 1, outf< 1 ch,      0 Hz, Float32> inf< 1 ch,  48000 Hz, Int16>)
App[13956:3993378] [aurioc]            AURemoteIO.cpp:1139  failed: 561017449 (enable 1, outf< 1 ch,      0 Hz, Float32> inf< 1 ch,  48000 Hz, Int16>)
...
App[14038:4007966] ERROR[OpenTok]:Audio device error: startCapture.AudioOutputUnitStart returned error: !pri
```

Also, we've experimented both with and without the recommended use of `OTDefaultAudioDevice`, which is initialized before the call to `CXProvider.reportNewIncomingCall`. No change.

**Comment by IGitGotIt** [comment]
Just so we narrow down the issue more, can you initialize the background publisher with audioTrack = false and check if you get the same error. If it works it can be an audio driver acquisition issue (maybe some other app else is playing audio or CallKit itself is playing a ringtone etc..). 
Thanks

**Comment by knightcode** [comment]
Actually, I'm not able to publish audio at all... even when the app is active. The session connects; all parties can publish and receive video, but no audio is received from iOS devices. With the `DefaultAudioDevice` from the custom audio driver sample, we sometimes get a few moments of audio before it cuts out. Without setting a custom audio device, ...nothing.

Also, the OTPublisher.init() is now hanging the main thread. Should that be created in the background?

**Comment by IGitGotIt** [comment]
I recommended turning off audioTrack so we can narrow the issue and diagnose the problem. It was not a solution and yes, audio will not work , if there is no audioTrack. With the publisher now publishing,  we now know it does not succeed with audio driver acquisition originally,  and  timeouts.

My guess, w/o looking at your code , is that you need to activate the audio rendering and capturing whenever your logic/flow dictates. Till then the audio drivers will be in a passive mode.  We have an ObjC sample [app](https://github.com/opentok/opentok-ios-sdk-samples/tree/main/Ringtones) , which  serializes audio driver acquisition, while a ringtone plays first.  Maybe you need to implement something similar to it .

**Comment by knightcode** [comment]
Oh, to clarify, the audio would cease with audioTrack=true. CallKit seemed to be doing something. A route change coincides with the didActivate call.

**Comment by knightcode** [comment]
Both our use cases are currently broken. These are the steps we perform for each

### PushKit Initiated
1. Receive Notification
2. Call `OTAudioDeviceManager.setAudioDevice(audioController!)` setting to an instance of `DefaultAudioDevice` from this repo
3. Call CXProvider.reportNewIncomingCall()
4. User Accepts Call, reported by `CXProviderDelegate.provider(_, perform: CXAnswerCallAction)`
5. Call `DefaultAudioDevice.startCapture()`
6. Create publisher: `OTPublisher(delegate:settings:)`, `videoTrack=true` and `audioTrack=true`
7. Set `OTPublisher.publishVideo=false`, `OTPublisher.publishAudio=true`
8. Create session: `OTSession(apiKey:sessionId:delegate)`
9. Call `OTSession.connect()`
10. Wait for `sessionDidConnect()` callback, then
11. Call `OTSession.publish()`
12. Receive `session(_:streamCreated:OTStream)` as usual
13. Eventually receive `publisher(_:didFailWithError:OTError)` with the timeout
14. Call `action.fail()` on the CXAnswerCallAction from step 4 because of the timeout (would call `action.fulfill()` on successful publish).

### User Initiated
1. Create publisher: `OTPublisher(delegate:settings:)`, `videoTrack=true` and `audioTrack=true` (we offer a selfie preview to the user before they join a session)
2. Set `OTPublisher.publishVideo=true`, `OTPublisher.publishAudio=true`
3. Call `OTAudioDeviceManager.setAudioDevice(audioController!)` setting to an instance of `DefaultAudioDevice` from this repo
4. Create session: `OTSession(apiKey:sessionId:delegate)`
5. Call `OTSession.connect()`
6. Wait for `sessionDidConnect()` callback, then
7. Call `OTSession.publish()`
8. Receive `session(_:streamCreated:OTStream)`, hold on subscribing until publish succeeds
9. Eventually receive `publisher(_:didFailWithError:OTError)` with the timeout

At other times, the publishing would succeed for the User Initiated flow, but only a few moments of audio would publish before the outgoing stream went silent. In that case, we would do the following:

9. Wait for publish success: `publisher(_:streamCreated:OTStream)`
10. Call `DefaultAudioDevice.startCapture()`
11. Create `CXStartCallAction` transaction for CXCallController. The system knows we're in a call now.
12. Subscribe to all held streams
17. Log a few called to `DefaultAudioDevice.recordCb`
18. Log a last call to `DefaultAudioDevice.onRouteChangeEvent` before calls to `recordCb` stopped.

**Comment by knightcode** [comment]
Seeing this error now:
```
ERROR[OpenTok]:Audio device error: startCapture.AudioOutputUnitStart returned error: what
```

By removing any use of the DefaultAudioDevice and the CXCallController, I was able to make the User Initiated flow above work on a second device, but not my primary phone. Reintroducing the DefaultAudioDevice still allowed the second device to work, but the primary device still timed out publishing. Adding back the calls for CXCallController, the secondary device would publish audio for a few moments and then go silent after the CXCallController did its thing and fired its `didActivate:AVAudioSession` callback in response to the `CXStartCallAction` described above. The primary device again had no change.

DefaultAudioDevice fails at `startCapture()`. It gets an error result from `AudioOutputUnitStart`, which doesn't always coincide with the error message listed at the top of this post. That message is absent.

**Comment by knightcode** [comment]
Error in DefaultAudioDevice.setupAudioSession() during PushKit flow:
```
Error setting up audio session Error Domain=NSOSStatusErrorDomain Code=561017449 "Session activation failed" UserInfo={NSLocalizedDescription=Session activation failed}
```

It fails at the `try session.setActive(true)` call.

**Comment by knightcode** [comment]
Found a  possible solution/work-around the User Initiated Flow. The `startCapture()` method of `DefaultAudioDevice` is called automatically by the OpenTok SDK. I'm not sure where. The backtrace just had it on the WebRTCThread, so that I'm not sure what queued it. In any case, by making this a no-op, I was able to call it manually in the `CXProviderDelegate.provider(_:didActivate:AVAudioSession)` callback. This, btw, was how my DefaultAudioDevice was already set up, only it was calling `startCapture()`, which I guess had already been called earlier. So I'm guessing the latest update changed that behavior. 

Still having an issue with the PushKit Initiated flow.

**Comment by knightcode** [comment]
Found some better behavior with the PushKit flow by moving the `action.fulfill()` earlier in the flow when the `sessionDidConnect()` callback. Fulfilling the action lets CallKit proceed to calling `CXProviderDelegate.provider(_:didActivate:AVAudioSession)`, and that's when the audio can be set up, session.publish(), and any outstanding streams can be subscribed to.

With this, the printed errors are reduced to:
```
2022-11-09 17:48:57.609935-0500 WorkBeta[18066:2488628] [as] ATAudioSessionPropertyManager.mm:89    Error 2003329396 while getting property value from AVAudioSession
```

CoreAudio repeatedly triggers `recordCb` and `renderCb` for 15 seconds, and then the publishing timeout error still occurs.

**Comment by knightcode** [comment]
Working Flows for anyone who might come across this in the future.

One change to DefaultAudioDevice: remove `AVAudioSession.sharedInstance().setActive(true)` from `setupAudioSession()`. This is handled by CallKit. I reverted the change discussed above that moved the `startCapture()` functionality to a different function. By holding all publish and subscribe calls, we can, in turn, hold off on the SDK from calling `startCapture()`. The custom audio driver is also necessary to be able to call to `setupAudioSession()` earlier than `session.publish()` would, specifically in the CXProviderDelegate callback. 

### User Initiated Flow (Outgoing call)
1. Call `OTAudioDeviceManager.setAudioDevice(audioController!)` setting to an instance of `DefaultAudioDevice`
2. Create publisher: `OTPublisher(delegate:settings:)`, `videoTrack=true` and `audioTrack=true`
3. Set `OTPublisher.publishVideo=true`, `OTPublisher.publishAudio=true`
4. Create session: `OTSession(apiKey:sessionId:delegate)`
5. Call `OTSession.connect()`
6. Wait for sessionDidConnect() callback, then
7. Receive session(_:streamCreated:OTStream), hold on subscribing until publish succeeds
8. Call `DefaultAudioDevice.setupAudioSession()`
9. Create and send CXStartCallAction transaction for CXCallController.
10. Wait for `CXProviderDelegate.provider(_:didActivate:AVAudioSession)`, then
11. Finally Call `OTSession.publish()`
12. Wait for publish success: `publisher(_:streamCreated:OTStream)`, then
13. Subscribe to all held streams

### PushKit Flow (Incoming Call)
1. Receive Notification
2. Call `OTAudioDeviceManager.setAudioDevice(audioController!)` setting to an instance of `DefaultAudioDevice`
3. Call `CXProvider.reportNewIncomingCall()`
4. User Accepts Call, reported by `CXProviderDelegate.provider(_, perform: CXAnswerCallAction)`
5. Call `DefaultAudioDevice.setupAudioSession()`
6. Create publisher: `OTPublisher(delegate:settings:)`
7. Set `OTPublisher.publishVideo=false`, `OTPublisher.publishAudio=true`
8. Create session: `OTSession(apiKey:sessionId:delegate)`
9. Call `OTSession.connect()`
10. Wait for `sessionDidConnect()` callback, then
11. Receive `session(_:streamCreated:OTStream)` as usual, queue streams for later subscription
12. Call `action.fulfill()` on earlier `CXAnswerCallAction`
13. Wait for `CXProviderDelegate.provider(_:didActivate:AVAudioSession)`, then
14. Call `OTSession.publish()`
12. Wait for publish success: `publisher(_:streamCreated:OTStream)`, then
13. Subscribe to all held streams

The downside of this is that the system's calling UI (used when you don't unlock the phone) moves from a "connecting" state to a "in progress" state with the upwardly counting timer as soon as `action.fulfill()` is called, but no streams are published or subscribed at that moment. So there's a few moments silence when the user expects to be able to start talking.

Leaving this open so that the dev's still address the timeout I was getting before.

**Comment by v-kpheng** [comment]
Any ideas, @IGitGotIt?

**Comment by hieultse03355** [comment]
I got this issue also. I am using tokbox version 2.18.1. Any ideas about this. Please

**Comment by hieultse03355** [comment]
I got it. So when Publisher timeout  then I can re-doPublish it again until it can be published? @IGitGotIt thank you so much

**Comment by IGitGotIt** [comment]
> I got it. So when Publisher timeout then I can re-doPublish it again until it can be published? @IGitGotIt Thank you so much

Yes that would be the suggested way. You can republish  ,  and again after 2 seconds or so, if it failed on the first retry. If it still does not work , on a regular basis, there is something inherently wrong in the app code. 

The retry typically helps if it was a network issue or some device media lock on audio/camera working it way out. Else not.

**Comment by hieultse03355** [comment]
I found out that when my app are in background and somewhere in your device is holding access to camera or microphone( watching video, recording video, recording voice) then receive a call, my app is going to use  OTDefaultAudioDevice  to init AudioUnit and try to set it to OTAudioDeviceManager through this code: 
![Screenshot 2023-04-11 at 10 35 02](https://user-images.githubusercontent.com/14196282/231049573-6061aa6f-a08c-4d5a-972f-7814ce85517a.png)
BUT sometime it can not init AudioUnit (because OTDefaultAudioDevice  not in main to take back access to camera or microphone) and throws some error like this: 
ERROR[OpenTok]:Audio device error: setupAudioUnit.AudioUnitInitialize returned error: 268451843
SOLUTION: when you received a VOIP notification, you try to preheat your audio session and after that, you have to call OTDefaultAudioDevice and set it to  OTAudioDeviceManager  on the main thread of your application :
![Screenshot 2023-04-11 at 10 59 03](https://user-images.githubusercontent.com/14196282/231052660-3da68d12-8c78-423d-92d6-575e21c0b5d9.png)
I hope this may help someone
