### ISSUE TITLE
Subscriber Video Enabling Problem

### ISSUE THREAD

**Issue by cemkazim** [opentok/opentok-ios-sdk-samples-swift#185]
When we activate the video after starting the conversation by enabling only the audio stream without enabling the video, the subscriberView doesn't appear on the iOS app. But when we go background and foreground just once, the video has appeared on the view.

If subscriber video opens, we want to see it in view.

iOS SDK version: 2.24.0
OS and version: 16.0

**Comment by david-wisq** [comment]
@pardel @abdulajet We're having the same issue here with the latest SDK version (**2.24.1**). Do we have an ETA or workaround for this issue? 

iOS version: 16.2

**Comment by v-kpheng** [comment]
Is this still reproducible on the latest version of the SDK, 2.25.3?
