### ISSUE TITLE
Latency of 10sec between the call of doPublish() and the call of session.publish()

### ISSUE THREAD

**Issue by ClaireRimel** [opentok/opentok-ios-sdk-samples-swift#186]
Xcode `14.0`
OpenTok via CocoaPods, pod version `2.24.0`
iOS SDK version `16.1`

With this 2.24.0 version I observe a latency of 10sec between the call of doPublish() and the call of session.publish(publisher, error: &error) which make the view freezing during the 10sec.
![2 4 0Version](https://user-images.githubusercontent.com/43319552/200547986-93fc20e8-1691-47fa-be29-4ee3cc081a23.png)

On 2.23.1 version this latency was around 1-2 seconds
![2 23 1Version](https://user-images.githubusercontent.com/43319552/200548029-2394fc2d-ba0f-400d-99bb-4a5f2fb260b9.png)

Here the Sample of my code
![code_sample](https://user-images.githubusercontent.com/43319552/200548105-3b0a3cf3-cc94-4b9e-bf7b-5fd8cb7b571c.png)

How is it possible to reduce this latency?

**Comment by v-kpheng** [comment]
Thanks, @ClaireRimel, for filing this issue.  

We're tracking this internally: https://jira.vonage.com/browse/OPENTOK-49706.

**Comment by beHaze** [comment]
Will be available in 2.24.1 release.

**Comment by ClaireRimel** [comment]
Wonderful job !!! 
Thank you !!!  

<img width="359" alt="Screenshot 2022-12-20 at 16 55 37" src="https://user-images.githubusercontent.com/43319552/208710449-c7538d81-8f97-4776-825d-f3919d2f93cc.png">
