### ISSUE TITLE
How do you stop a Publisher that is not published to a session?

### ISSUE THREAD

**Issue by derekpitts28** [opentok/opentok-ios-sdk-samples-swift#205]
In our use case we create a publisher that shows a preview of the users camera to the user BEFORE connecting to the session. Currently i see no way to 'stop' the publisher. The android SDK has an onStop call that stops the camera but there is no such call in the iOS SDK.

**Comment by goncalocostamendes** [comment]
@derekpitts28 the best way to stop the camera while on preview is to simply call `[_publisher setPublishVideo:false];` which will stop the video and release the capturer. To display it simply call `[_publisher setPublishVideo:true];`

**Comment by goncalocostamendes** [comment]
@derekpitts28 I hope your doubt was cleared. I've also answered the same question on your Android and iOS sample repos. I will close the ticket. If you still have any doubts, please let me know
