### ISSUE TITLE
Crash using BlueTooth headset

### ISSUE THREAD

**Issue by tankadesign** [opentok/opentok-ios-sdk-samples-swift#33]
Crashes at line 276: estimatedCaptureDelay
Tested on: iPhone 6/iOS 9.3.5 and iPhone 7+/iOS 10.3.1
Bluetooth devices tested: Jaybird X and Big Jambox

Also, audio quality on bluetooth is horrible ... sounds like it's 8 bit audio. The same quality issue is true in the Objective C example.

**Comment by MichaelJolley** [comment]
Closing as stale. Please open a new issue if the problem or question persists.
