### ISSUE TITLE
Can not get data from the 'subscriber'

### ISSUE THREAD

**Issue by aprecode** [opentok/opentok-ios-sdk-samples-swift#41]
By using Basic video chat example, I tried to create a session between the web browser and the app. Data from the publisher(mobile) can be seen on the browser but subscriber data does not appear on the app.

In order not to use the mobile as subscriber also, I changed 'subscribeToSelf' value as 'false'. In this case, it does not reaches to the 'subscriberDidConnect' function.

I'll be glad if you can show me a way to make the app recognize browser as subscriber.

**Comment by msach22** [comment]
@aprecode Apologies for the delay on this one. Are you still facing this issue?
