### ISSUE TITLE
Multiparty UICollectionView Sample App not responding to orientation while session is active

### ISSUE THREAD

**Issue by justindunn** [opentok/opentok-ios-sdk-samples-swift#42]
In Multiparty UICollectionView, we've noticed that if you go from portrait to landscape or landscape to portrait during a session the child views do not respond accurately, it remains cut off at the bottom. The screen flips but the views do not, is there a way to fix this? We also noticed that sometimes the landscape views crop off the top and bottom of the feeds.

**Comment by justindunn** [comment]
still wondering about this issue, has anyone had any luck?

**Comment by yusuftor** [comment]
What version have you been using? I have an issue with orientation. The last version that works is 2.14.2, all the others do not update the videoDimensions property of a stream correctly.
