### ISSUE TITLE
Seeing "55: EXCEPTION (-1)" logged repeatedly when using Custom Audio Driver example.

### ISSUE THREAD

**Issue by ppierson** [opentok/opentok-ios-sdk-samples-swift#46]
I've imported DefaultAudioDevice.swift into my app and am calling:
```
OTAudioDeviceManager.setAudioDevice(DefaultAudioDevice.sharedInstance)
```

When I connect to a session I repeatedly see an exception in the logs:
```
2017-10-24 15:22:05.606077-0400 Anchor[6321:1328636] 55: EXCEPTION (-1): ""
2017-10-24 15:22:05.615786-0400 Anchor[6321:1328636] 55: EXCEPTION (-1): ""
2017-10-24 15:22:05.628220-0400 Anchor[6321:1328636] 55: EXCEPTION (-1): ""
```

**Comment by ppierson** [comment]
Also I am getting issues where participants in the session are unable to hear any audio from other participants. This only happens when using the custom audio driver in the example.

**Comment by robjperez** [comment]
Audio driver sample has been updated and this should be a problem.

Closing the ticket

**Comment by theronic** [comment]
What was the issue? I'm seeing the same WebRTC error on an unrelated project.

**Comment by robjperez** [comment]
Our audio driver implementation is inspired by webrtc one. We fixed that problem in this PR: https://github.com/opentok/opentok-ios-sdk-samples-swift/pull/47/files

The problem was related to the AudioUnit properties handling.
