### ISSUE TITLE
ExampleVideoCapture tilts in the wrong direction for front camera

### ISSUE THREAD

**Issue by tkrajacic** [opentok/opentok-ios-sdk-samples-swift#48]
In the custom video driver example, if you slightly rotate the camera, the video is tilted in the wrong direction when using the front camera. Switching to the back camera makes the preview layer rotate correctly.

The tilt I am talking about is what the layer does to mitigate device tilt until the UI finally rotates completely.

**Comment by tkrajacic** [comment]
Actually I think the entire image is just mirrored and that's where the problem is rooted.

**Comment by MichaelJolley** [comment]
Closing as stale. Please open a new issue if the problem or question persists.
