### ISSUE TITLE
help with swift 4

### ISSUE THREAD

**Issue by boardmain** [opentok/opentok-ios-sdk-samples-swift#49]
hi after ugrading to swift 4 i see this error in
VideoCaputre.swift

Expression pattern of type 'AVCaptureSession.Preset' cannot match values of type 'String'

in extension String {
    func dimensionForCapturePreset() -> (width: UInt32, height: UInt32) {

can you help?

**Comment by boardmain** [comment]
in the same file i have the error for
AVCaptureDevice.Format.FrameRateRange

and


glActiveTexture(UInt32(GL_TEXTURE0 + index)) (+ is unavailable) in the EAGLVideoRender.swift file

**Comment by robjperez** [comment]
Hi @boardmain 

The master branch of the repo is not Swift 4 compatible, however there is a branch with the required changes to build with swift 4. See https://github.com/opentok/opentok-ios-sdk-samples-swift/tree/swift4-support

We will eventually merge that branch into master branch

Please reopen the issue if you are still having problems with that branch.
