### ISSUE TITLE
How to change TokBox audio volume programmatically? 

### ISSUE THREAD

**Issue by Igorsnaki** [opentok/opentok-ios-sdk-samples-swift#51]
Hi all! 

We use ios openTok sdk for our app. 
We have requirement to change audio volume on tokbox session programmatically using slider for changing volume. 
Are there any ways to do this? I can't find any OTSubscriber, OTSession, OTPublisher and other classes interfaces which allow me to do this. 
Help please.

**Comment by robjperez** [comment]
Hi @Igorsnaki 

OpenTok SDK has no volume control support bundled in. To do so, you need to implement you own AudioDriver, 

To know more about implementing your own audio driver, please take a look to the custom audio driver sample in this repo: https://github.com/opentok/opentok-ios-sdk-samples-swift/tree/master/Custom-Audio-Driver

We have not ported to swift the volume control part, so please take a look to the ObjC class here: https://github.com/opentok/opentok-ios-sdk-samples/blob/master/Custom-Audio-Driver/External-Audio-Device/OTDefaultAudioDeviceWithVolumeControl.m

If you have problems porting the code to swift or understanding how a custom driver help, please don't hesitate to comment in the issue.
