### ISSUE TITLE
Keep the same aspect ratio whenever the screen is landscape or portrait

### ISSUE THREAD

**Issue by neophyteKB** [opentok/opentok-ios-sdk-samples-swift#60]
when device is in landscape mode the subscriber video get cropped , suggest method to keep video ratio same in both landscape and portrait mode

**Comment by Lucashuang0802** [comment]
@neophyteKB is there a specific project you are referring to or things in general here?

**Comment by marcoserafini2** [comment]
@neophyteKB have you solved it ?
