### ISSUE TITLE
Destroyed stream when one participant joins the session after being in background mode.

### ISSUE THREAD

**Issue by thibaultleconte** [opentok/opentok-ios-sdk-samples-swift#68]
This is based on https://stackoverflow.com/questions/51391291/opentok-ios-best-practice-to-start-a-video-chat-when-one-participant-has-the/51432279#51432279

We have Participant A and Participant B.

A triggers sessionDidConnect
A triggers session streamCreated
A pauses the app. The app is running in background
B triggers sessionDidConnect
B triggers session streamCreated
When A brings the app to foreground, then the connection and stream get destroyed. I would like to understand what we are doing wrong.

When is the best moment to call the following methods?

session.publish(publisher, ...)
session.subscribe(subscriber, ...)

I followed your documentation from tokbox.com/developer/sdks/ios/background-state.html when I initially set up the SDK and everything seems ok.

**Comment by MichaelJolley** [comment]
Closing as stale. Please open a new issue if the problem or question persists.
