### ISSUE TITLE
Example 2 (and thus 5) do not work properly

### ISSUE THREAD

**Issue by chrisscholly** [opentok/opentok-ios-sdk-samples-swift#7]
I'm testing on an iPhone 7.
Any idea pls?

![img_0041](https://cloud.githubusercontent.com/assets/26509/22035265/9e294ade-dcef-11e6-92e1-22a8bd2deeb8.PNG)

**Comment by chrisscholly** [comment]
Note: Objective-C version works as well. The issue only occurs on Swift version.

**Comment by bdolman** [comment]
Yeah, I get the same thing

**Comment by dbarta** [comment]
I get the same images in swift. iPhone 5s, Xcode 8.3

**Comment by sagardesai16** [comment]
Even I get the same issue. Any solution so far?

**Comment by robjperez** [comment]
Thanks for reporting it.
It will now be fixed with the last commit.
