### ISSUE TITLE
OpenTok publisher's view becomes black when application enters in foreground

### ISSUE THREAD

**Issue by Zeeshan03422** [opentok/opentok-ios-sdk-samples-swift#75]
In my one to one video calling app using OpenTok, the publisher's view becomes black after it goes to background mode and enters foreground. The subscriber is also not able to see the view(only seeing black box).

I am setting the publisher and subscriber properties as such:

publisher.publishVideo = true
subscriber.subscribeToVideo = true

Any solution will be very helpful.

**Comment by msach22** [comment]
@Zeeshan03422 Apologies for the delay in getting back to you. Are you still seeing this issue with the latest SDKs? Could you please share how long you're in the background before you come to foreground?

**Comment by Amishabigscal** [comment]
Yes I am too getting  this issue . App going background for 2 - 3 second and come to the foreground then publisher's view becomes black.

**Comment by Surendraiosdev** [comment]
Hello All,
Yes, i am also getting same issue publisher's view becomes black.
any solution for this issue then please let me know.
i using latest iOS SDk OpenTok (2.16.3)

publisher's unable to send streamvideo at subscriber side. how to fix.
thanks in advance.

**Comment by johnDaniul** [comment]
I am also seeing this issue in a project, using OpenTok iOS SDK 2.16.3. When returning to a foreground state, the publisher will basically stop randomly, with no obvious errors.

**Comment by jrz-afs** [comment]
I am seeing the same issue here as well. Any updates on this?

**Comment by IGitGotIt** [comment]
With  2.16.3.7978-ios on iPhone 7 using [Basic-Video-Chat](https://github.com/opentok/opentok-ios-sdk-samples-swift/tree/master/Basic-Video-Chat) swift app  and background mode capabilities like :
![image](https://user-images.githubusercontent.com/4369083/77802855-0191ca80-7039-11ea-8c0a-6b245ded0518.png)
I am not able to reproduce the issue.
I was in the background mode for 2-3 seconds, more than 30 seconds , went into lock mode and came back and I was still able to see the publisher active and streaming to subscriber on a Chrome browser.

Also tried it with SDK version 2.16.5 and did not see any difference.

If you can give me detailed steps I can investigate more. Also make sure you have the Background modes flag set as shown above.

**Comment by palmas** [comment]
I am also seeing this issue on android.

**Comment by palmas** [comment]
> @Zeeshan03422 Apologies for the delay in getting back to you. Are you still seeing this issue with the latest SDKs? Could you please share how long you're in the background before you come to foreground?

I am also seeing this issue on android. After approximately 1 minute in background  publisher's view becomes black and publisher is unable to send stream video at subscriber side. 

OpenTok sdk version: 2.16.5,
Android version: 9.0

**Comment by Eratos1122** [comment]
The background mode is enabled but the publisher screen becomes black if I lock my iPhone

**Comment by msach22** [comment]
@Eratos1122 This is a limitation from the iOS platform, you cannot access the camera in background mode which is why the screen becomes black when you lock your iPhone.

**Comment by Eratos1122** [comment]
> @Eratos1122 This is a limitation from the iOS platform, you cannot access the camera in background mode which is why the screen becomes black when you lock your iPhone.

It becomes black when the app is active after a while

**Comment by vanboren** [comment]
@msach22 I also having this issue with the latest sdk 2.18.1 on ios 14. When the app goes background and then foreground publisher video freeze and turns into black screen. Subscriber video have no problem and also my audio still remains.
