### ISSUE TITLE
'consumeFrame' crashes when using a modified pixel buffer

### ISSUE THREAD

**Issue by thorng** [opentok/opentok-ios-sdk-samples-swift#80]
Hi, I have taken the Custom-Video-Driver example project and updated it to Swift 4.2. Then I tried taking the image buffer, modifying it (using Vision and Core Image), then return it for consumption by OpenTok. However, every time I try to do so, I get the error on the first frame: 

> *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSConcretePointerArray pointerAtIndex:]: attempt to access pointer at index 1 beyond bounds 1'

Here is my code:

     func captureOutput(_ output: AVCaptureOutput, didOutput sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection) {
        if !capturing || videoCaptureConsumer == nil {
            return
        }
        
        guard let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer)
            else {
                print("Error acquiring sample buffer")
                return
        }
                
        guard let videoInput = videoInput
            else {
                print("Capturer does not have a valid input")
                return
        }
        
        let time = CMSampleBufferGetPresentationTimeStamp(sampleBuffer)
        
        videoFrame.timestamp = time
        let height = UInt32(CVPixelBufferGetHeight(imageBuffer))
        let width = UInt32(CVPixelBufferGetWidth(imageBuffer))
        
        if width != captureWidth || height != captureHeight {
            updateCaptureFormat(width: width, height: height)
        }
           
        guard let finalImage = makeBigEyes(imageBuffer) else { return }
        
        CVPixelBufferLockBaseAddress(finalImage, CVPixelBufferLockFlags(rawValue: 0))
        
        videoFrame.format?.estimatedCaptureDelay = 10
        videoFrame.orientation = .left
        
        videoFrame.clearPlanes()
        videoFrame.planes?.addPointer(CVPixelBufferGetBaseAddress(finalImage))
        
        delegate?.finishPreparingFrame(videoFrame)
        
        videoCaptureConsumer!.consumeFrame(videoFrame)
        
        CVPixelBufferUnlockBaseAddress(finalImage, CVPixelBufferLockFlags(rawValue: 0))
    }

I am wondering if this is an OpenTok API issue or my own. I've tried many things but don't quite get the error. Why is it it trying to access index 1 on the first frame?

**Comment by robjperez** [comment]
Which image format is your `makeBigEyes` returning?

In the sample, opentok library is expecting to have a planar YUV image, if `makeBigEyes` is returning a different image format (like RGBA), it won't work.
