### ISSUE TITLE
Custom Video Driver shows black publisher (Swift 4.2 - Xcode 10.1)

### ISSUE THREAD

**Issue by ozkansari37** [opentok/opentok-ios-sdk-samples-swift#84]
The sample project Custom-Video-Driver not working as expected. All opentok credentials are replaced correctly and I can see subscriber. But publisher frame is blank. Publish not started and publish stream not created.

**Comment by Vol-i** [comment]
Same here, publisher frame is blank.

**Comment by designtesbrot** [comment]
Same here Xcode 10.2.1

**Comment by imentos** [comment]
same here

**Comment by Nachot93** [comment]
Same here, also crashes saying: `Multiple audio/video AVCaptureInputs are not currently supported`

**Comment by magora-obukhov** [comment]
+ 1

**Comment by designtesbrot** [comment]
@robjperez (seems to be the maintainer) it looks like there are several people facing this issue. Without having source code access, is there anything we can do to support? For us the issue seems to be related with using routed sessions.

**Comment by alrik** [comment]
Same for me. Cannot get ṕublishing on routed sessions to work with latest iOS SDK.

**Comment by robjperez** [comment]
Hi, 

Sorry for the delay, but it should be fixed in #92

**Comment by robjperez** [comment]
Now that the PR is merged, it should be fixed.
Going to close the issue, please reopen it if necessary
