### ISSUE TITLE
Orientation issues

### ISSUE THREAD

**Issue by yusuftor** [opentok/opentok-ios-sdk-samples-swift#87]
I have contacted tokbox support a couple of times with a sample app demonstrating this problem but the support seems to be very slow. I'll try posting on here to see if I can reach out to the developers, as this is becoming an urgent problem.

Essentially, version 2.14.2 of OpenTok was the last version to correctly update the videoDimensions property of a stream that you're subscribed to. Ever since then, the videoDimensions for the stream have been incorrect. For this reason I cannot reliably upgrade my OpenTok version. Please can someone fix this?

I have attached a modified version of the `Simple-Multiparty` sample code. Please install pods. Also try installing with version 2.14.2 and see the difference in console logs! Here are the instructions:

1. Have two devices streaming to each other in the session, and make sure they’re both subscribed to each other and the streams have been created.
2. Rotate one device and look at the value of the videoDimensions printed out in the logs. Every time you rotate the device, the dimensions of the stream will always be the same. This should not happen, the width and height values should change based on the rotation of the device.

An example log should look like this:

`video dimensions of stream changed to Optional([__C.NSKeyValueChangeKey(_rawValue: kind): 1, __C.NSKeyValueChangeKey(_rawValue: new): NSSize: {720, 1280}])`

[opentok-ios-sdk-samples-swift-master-3.zip](https://github.com/opentok/opentok-ios-sdk-samples-swift/files/3321044/opentok-ios-sdk-samples-swift-master-3.zip)

**Comment by bsrao** [comment]
This was fixed in 2.16.3
