### ISSUE TITLE
Not able to see subscriber videos 

### ISSUE THREAD

**Issue by vaibhavTesting** [opentok/opentok-ios-sdk-samples-swift#88]
Using Publisher token I can able to see only publisher video.
 How can I see the subscriber's(who are using subscriber token but the same session id) video who connected with the same session with Publisher?

**Comment by msach22** [comment]
A subscriber can only subscriber - they cannot publish. This is why someone using the subscriber token will not be able to publish. For more information, please check out the following guide: https://tokbox.com/developer/guides/create-token/
