### ISSUE TITLE
55: EXCEPTION (-1): "" when writing to an audio session.

### ISSUE THREAD

**Issue by minuscorp** [opentok/opentok-ios-sdk-samples-swift#96]
I'm currently writing capture data from a sample of 48000hz sin signal just for testing purposes. When I start to send the audio packets as they come from BLE and decompressed to have the same format as TokBox (1 channel, 48000hz, 16bit signed integer) I start to get the following error:

`2019-09-06 15:14:30.609207+0200 ElluListenerExample[570:47449] [aid] AudioIssueDetectorNode.cpp:161:Initialize: Caught analyzer graph exception 1718775073 !mrf slice duration must be set before configure. in /BuildRoot/Library/Caches/com.apple.xbs/Sources/AudioDSP/AudioDSP-251.70.4.1/CoreAudioUtility/Source/CADSP/DSPGraph/DSPGraph_Graph.cpp:597
2019-09-06 15:14:30.663720+0200 ElluListenerExample[570:47505] 55: EXCEPTION (-1): ""`

And shortly after the application crashes.
The code to inject the audio is pretty straightforward:

```

dispatch_async(dispatch_get_main_queue(), ^{
[manager.audioDevice.deviceAudioBus writeCaptureData: ioData->mBuffers[0].mData numberOfSamples:inNumberFrames];
});

```

Any idea of what is crashing inside the framework?

**Comment by bsrao** [comment]
@minuscorp This issue was fixed in this version of the audio driver : https://github.com/opentok/opentok-ios-sdk-samples/blob/master/Custom-Audio-Driver/External-Audio-Device/OTDefaultAudioDevice.m
