### ISSUE TITLE
Crash on Basic Video Chat 

### ISSUE THREAD

**Issue by marinaf27** [opentok/opentok-ios-sdk-samples-swift#98]
Upon running the Basic Video chat, the application crash with Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

#0	0x000000010072ab38 in -[OTMTLVideoRenderer setupTexturesForFrame:] ()
<img width="1680" alt="Screenshot 2019-11-21 at 3 23 59 AM" src="https://user-images.githubusercontent.com/19539258/69320615-809c6f80-0c0f-11ea-9ab5-fb43eb57cd89.png">

**Comment by findigital** [comment]
I had the same issue - any resolution?
